# .github/workflows/ci.yml
name: web-ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      CI: 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'   # cache based on pnpm-lock.yaml

      # ✅ Always make pnpm available on PATH
      - name: Install pnpm
        run: npm i -g pnpm@9.7.0

      # Quick sanity check + PATH debug if ever needed
      - run: pnpm -v && node -v && which pnpm && echo "$PATH"

      # Install once at workspace root (monorepo-friendly)
      - name: Install deps (workspace root)
        run: pnpm -w install

      # Build only the web app
      - name: Build web
        run: pnpm -F web build
