# .github/workflows/ci.yml
name: web-ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      CI: 'true'
    steps:
      - uses: actions/checkout@v4

      # Node (adds Corepack, too)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'     # enables lockfile-based cache

      # ✅ Install pnpm and add it to PATH
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
          run_install: false

      # Sanity: prove pnpm is on PATH
      - run: pnpm -v && node -v

      # Install once at the workspace root (monorepo-friendly)
      - name: Install deps (workspace root)
        run: pnpm -w install

      # Build only the web app
      - name: Build web
        run: pnpm -F web build