# .github/workflows/ci.yml
name: web-ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: web-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      CI: 'true'
    steps:
      - uses: actions/checkout@v4

      # Node (adds corepack too, but we'll explicitly install pnpm next)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'   # cache based on pnpm-lock.yaml at repo root

      # ✅ Ensure pnpm is installed and on PATH
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
          run_install: false

      # Sanity check
      - run: pnpm -v && node -v

      # Workspace install at repo root (monorepo-friendly)
      - name: Install deps (workspace root)
        run: pnpm -w install

      # Build only the web app
      - name: Build web
        run: pnpm -F web build
